### ISSUE TITLE
Web 서버 / DB 모듈 및 페이지 만들기

### ISSUE THREAD

**Issue by qooklab** [Posehelper/Poses-maketh-man#7]
### 요구사항
test db 스키마 만들고
db 서버(mysql or  db sqlite)와 연결하는 모듈 설정해보고
db crud 해보는 페이지 까지 구성해보기(간단하게)

### Task

- [ ] flask 서버에 DB 모듈 붙이기
- [ ] 간단한 데이터 생성, 읽어오기, 수정, 삭제 해보는 서버 로직 구현( create, read, update, delete)
- [ ] web 페이지로 만들어보기
